const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)],rnd=a=>a[Math.floor(Math.random()*a.length)],fmt=n=>String(n).padStart(2,'0'),time=s=>fmt(Math.floor(s/60))+':'+fmt(s%60),acc=(c,t)=>t?Math.round(c/t*100)+'%':'0%';
const fractions=[];for(let d=2;d<=20;d++)for(let n=1;n<d;n++){let g=(a,b)=>b?g(b,a%b):a;if(g(n,d)===1)fractions.push({id:n+'-'+d,n,d,p:+(n/d*100).toFixed(1)})}
const unitFractions=fractions.filter(x=>x.n===1);
const make=(type,min,max,pow)=>Array.from({length:max-min+1},(_,i)=>{let n=i+min,r=type==='sqrt'?+Math.sqrt(n).toFixed(3):n**pow;return{id:type+n,n,r,expr:type==='sqrt'?'√'+n:n+'<sup>'+pow+'</sup>',show:type==='sqrt'?r.toFixed(3):String(r)}});
const data={square:make('square',1,50,2),cube:make('cube',1,30,3),fourth:make('fourth',1,20,4),sqrt:make('sqrt',2,100,0)};
const labels={square:'平方',cube:'立方',fourth:'四次方',sqrt:'平方根'};
const st={page:'percent',percent:{mode:'b2f',q:null,answer:'',status:'idle',feedback:'',total:0,correct:0,start:0,recent:[],deadline:0},memory:{cat:'square',dirMode:'forward',dir:'forward',q:null,answer:'',status:'idle',feedback:'',total:0,correct:0,start:0,recent:[]},cheat:{cat:'percent',query:''}};let timer=null,examDone=false;
function hero(title,sub,icon=''){return`<div class="hero">${icon?`<div class="book">${icon}</div>`:''}<h1>${title}</h1><p>${sub}</p></div>`}
function seg(items,active,attr){return`<div class="seg">${items.map(x=>`<button ${attr}="${x.v}" class="${x.v===active?'active':''}">${x.t}</button>`).join('')}</div>`}
function stats(s,id){return`<div class="stats"><div class="stat"><div><div class="ico">◷</div><strong id="${id}Time">${time(s.start?Math.floor((Date.now()-s.start)/1000):0)}</strong><span>用时</span></div></div><div class="stat"><div><div class="ico">◎</div><strong>${acc(s.correct,s.total)}</strong><span>正确率</span></div></div><div class="stat"><div><div class="ico">▧</div><strong>${s.total}</strong><span>已答题数</span></div></div></div>`}
function pick(arr,recent){let pool=arr.filter(x=>!recent.includes(x.id));return rnd(pool.length?pool:arr)}function addRecent(a,id){return [...a,id].slice(-5)}
function newPercent(mode=st.percent.mode,reset=false){clearTimeout(timer);let s=st.percent;if(reset)Object.assign(s,{total:0,correct:0,start:mode==='exam'?Date.now():0,recent:[],deadline:mode==='exam'?Date.now()+300000:0});s.mode=mode;let kind=mode==='mix'?rnd(['b2f','f2b']):mode==='exam'?rnd(['b2f','f2b']):mode;let source=kind==='b2f'?unitFractions:fractions;let f=pick(source,s.recent);s.recent=addRecent(s.recent,f.id);s.q={...f,kind};s.answer='';s.status='idle';s.feedback='';examDone=false;renderPercent()}
function percentView(q){if(q.kind==='b2f')return{badge:'百分数',prompt:'请输入对应的分数分母',main:q.p+'%',suffix:'= 1/?',ph:'输入分母'};return{badge:'分化百',prompt:'请输入对应的百分数',main:q.n+'/'+q.d,suffix:'= ?%',ph:'输入百分数'}}
function percentHint(mode){return mode==='b2f'?'百化分只练习 1/n 型题目；输入分母即可':mode==='f2b'?'分化百练习完整既约分数；输入百分数即可':'混合/考试会随机出现百化分与分化百题'}
function renderPercent(){let s=st.percent,q=percentView(s.q);$('#percent').innerHTML=hero('百化分记忆练习','公考资料分析速算技巧 · 每日一练')+seg([{v:'b2f',t:'百化分'},{v:'f2b',t:'分化百'},{v:'mix',t:'混合'},{v:'exam',t:'考试'}],s.mode,'data-pmode')+`<div class="card ${s.status==='ok'?'ok':s.status==='bad'?'bad':''}">${s.mode==='exam'?`<span class="exam" id="examLeft">${time(examLeft())}</span>`:''}<span class="badge">${q.badge}</span><div class="prompt">${q.prompt}</div><div class="question"><span class="qmain">${q.main}</span><span class="suffix">${q.suffix}</span></div></div><form class="answer" id="pform"><input id="pinput" inputmode="decimal" autocomplete="off" spellcheck="false" placeholder="${q.ph}" value="${s.answer}"><button class="primary">${/ok|bad/.test(s.status)?'下一题':'提交'}</button><button class="reset" type="button" title="重置">↻</button></form><div class="feedback ${s.status}">${s.feedback}</div>${stats(s,'p')}<p class="hint">${percentHint(s.mode)}</p>`;$$('[data-pmode]').forEach(b=>b.onclick=()=>newPercent(b.dataset.pmode,true));$('#pform').onsubmit=e=>{e.preventDefault();submitPercent()};$('#pinput').oninput=e=>s.answer=e.target.value;$('.reset',$('#percent')).onclick=()=>newPercent(s.mode,true);setTimeout(()=>$('#pinput')?.focus(),0)}
function parsePercentAnswer(raw,kind){raw=raw.trim();if(!raw)return{ok:false,empty:true,msg:'请先输入答案'};if(kind==='b2f'){if(!/^\d+(?:\.0+)?$/.test(raw))return{ok:false,msg:'请输入有效的整数分母'};let v=Number(raw);return v>0&&Number.isInteger(v)?{ok:true,value:v}:{ok:false,msg:'请输入有效的整数分母'}}let text=raw.endsWith('%')?raw.slice(0,-1).trim():raw;if(!/^\d+(?:\.\d+)?$/.test(text))return{ok:false,msg:'请输入有效百分数'};return{ok:true,value:Number(text)}}
function submitPercent(){let s=st.percent;if(/ok|bad/.test(s.status)){newPercent();return}if(s.mode==='exam'&&examLeft()<=0){finishExam();return}let q=s.q,parsed=parsePercentAnswer(s.answer,q.kind);if(!parsed.ok){s.feedback=parsed.msg;s.status='warn';renderPercent();return}if(!s.start)s.start=Date.now();let v=parsed.value,ok=q.kind==='b2f'?v===q.d:Math.abs(v-q.p)<.051;s.total++;if(ok)s.correct++;s.status=ok?'ok':'bad';s.feedback=ok?'✓ 正确：'+(q.kind==='b2f'?'1/'+q.d+' = '+q.p+'%':q.n+'/'+q.d+' = '+q.p+'%'):'✕ 正确答案：'+(q.kind==='b2f'?'1/'+q.d:q.p+'%');renderPercent();timer=setTimeout(()=>st.page==='percent'&&newPercent(),1100)}
function newMemory(cat=st.memory.cat,dirMode=st.memory.dirMode,reset=false){clearTimeout(timer);let s=st.memory;if(reset)Object.assign(s,{total:0,correct:0,start:0,recent:[]});s.cat=cat;s.dirMode=dirMode;s.dir=dirMode==='mix'?rnd(['forward','reverse']):dirMode;s.q=pick(data[cat],s.recent);s.recent=addRecent(s.recent,s.q.id);s.answer='';s.status='idle';s.feedback='';renderMemory()}
function memView(s){let q=s.q;if(s.dir==='forward')return{prompt:s.cat==='sqrt'?'请输入繳方根（保留三位小数）':'请输入'+labels[s.cat]+'的结果',main:q.expr,suffix:'= ?',ph:s.cat==='sqrt'?'输入繳方根结果':'输入计算结果'};return{prompt:s.cat==='sqrt'?'请输入对应的被开方数':'请输入对应的底数',main:q.show,suffix:s.cat==='sqrt'?'= √?':s.cat==='square'?'= ?²':s.cat==='cube'?'= ?³':'= ?⁴',ph:s.cat==='sqrt'?'输入被开方数':'输入底数'}}
function renderMemory(){let s=st.memory,v=memView(s);$('#memory').innerHTML=hero('数字记忆练习','平方 · 立方 · 四次方 · 平方根 · 公考速算必备')+seg([{v:'square',t:'繳方数'},{v:'cube',t:'立方数'},{v:'fourth',t:'四次方'},{v:'sqrt',t:'平方根'}],s.cat,'data-cat')+`<div class="direction">${seg([{v:'forward',t:'→ 正向'},{v:'reverse',t:'← 反向'},{v:'mix',t:'⤨ 混合'}],s.dirMode,'data-dir')}</div><div class="card ${s.status==='ok'?'ok':s.status==='bad'?'bad':''}"><span class="badge">${labels[s.cat]} · ${s.dir==='forward'?'正向':'反向'}</span><div class="prompt">${v.prompt}</div><div class="question"><span class="qmain">${v.main}</span><span class="suffix">${v.suffix}</span></div></div><form class="answer" id="mform"><input id="minput" inputmode="decimal" autocomplete="off" spellcheck="false" placeholder="${v.ph}" value="${s.answer}"><button class="primary">${/ok|bad/.test(s.status)?'下一题':'提交'}</button><button class="reset" type="button">↻</button></form><div class="feedback ${s.status}">${s.feedback}</div>${stats(s,'m')}<p class="hint">平方根答案需四舍五入保留三位小数</p>`;$$('[data-cat]').forEach(b=>b.onclick=()=>newMemory(b.dataset.cat,s.dirMode,true));$$('[data-dir]').forEach(b=>b.onclick=()=>newMemory(s.cat,b.dataset.dir,true));$('#mform').onsubmit=e=>{e.preventDefault();submitMemory()};$('#minput').oninput=e=>s.answer=e.target.value;$('.reset',$('#memory')).onclick=()=>newMemory(s.cat,s.dirMode,true);setTimeout(()=>$('#minput')?.focus(),0)}
function submitMemory(){let s=st.memory;if(/ok|bad/.test(s.status)){newMemory();return}if(!s.answer.trim()){s.status='bad';s.feedback='请先输入答案';renderMemory();return}if(!s.start)s.start=Date.now();let v=parseFloat(s.answer),ok=s.dir==='reverse'?v===s.q.n:s.cat==='sqrt'?Math.abs(v-s.q.r)<.00051:v===s.q.r;s.total++;if(ok)s.correct++;s.status=ok?'ok':'bad';s.feedback=ok?'✓ 正确：'+plain(s.q.expr)+' = '+s.q.show:'✕ 正确答案：'+plain(s.q.expr)+' = '+s.q.show;renderMemory();timer=setTimeout(()=>st.page==='memory'&&newMemory(),1100)}
function plain(x){return x.replace('<sup>2</sup>','²').replace('<sup>3</sup>','³').replace('<sup>4</sup>','⁴')}
function cheatRows(cat,q){let rows=cat==='percent'?fractions.map(x=>[x.n+'/'+x.d,x.p+'%']):data[cat].map(x=>[x.expr,x.show]);q=q.trim().toLowerCase();return q?rows.filter(x=>(plain(x[0])+' '+x[1]).toLowerCase().includes(q)):rows}
function renderCheat(){let s=st.cheat,items=[{v:'percent',t:'百分分数'},{v:'square',t:'平方'},{v:'cube',t:'立方'},{v:'fourth',t:'四次方'},{v:'sqrt',t:'平方根'}],rows=cheatRows(s.cat,s.query),name=items.find(x=>x.v===s.cat).t;$('#cheat').innerHTML=hero('记忆速查表','公考速算必备公式 · 随时翻阅背诵','▤')+`<div class="tools">${seg(items,s.cat,'data-ccat')}<div class="searchbox"><input class="search" id="search" placeholder="搜索${name}…" value="${s.query}"></div></div><span class="meta">${name} · 共 ${rows.length} 条</span><div class="panel">${rows.length?`<div class="grid">${rows.map(x=>`<div class="item"><span>${x[0]}</span><span class="arrow">→</span><b>${x[1]}</b></div>`).join('')}</div>`:'<div class="empty">没有找到匹配内容</div>'}</div>`;$$('[data-ccat]').forEach(b=>b.onclick=()=>{s.cat=b.dataset.ccat;s.query='';renderCheat()});$('#search').oninput=e=>{s.query=e.target.value;let pos=e.target.selectionStart;renderCheat();$('#search').focus();$('#search').setSelectionRange(pos,pos)}}
function switchPage(p){st.page=p;$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$$('.page').forEach(x=>x.classList.add('hide'));$('#'+p).classList.remove('hide');p==='percent'?renderPercent():p==='memory'?renderMemory():renderCheat();scrollTo({top:0,behavior:'smooth'})}
function examLeft(){return Math.max(0,Math.ceil((st.percent.deadline-Date.now())/1000))}function finishExam(){if(examDone||st.percent.mode!=='exam'||!st.percent.deadline)return;examDone=true;clearTimeout(timer);let s=st.percent;$('#modal').innerHTML=`<div class="modal"><div><h2>考试结束</h2><p>本次共完成 <b>${s.total}</b> 题，答对 <b>${s.correct}</b> 题，正确率为 <b>${acc(s.correct,s.total)}</b>。</p><div class="actions"><button class="primary" id="again">重新开始</button><button class="ghost" id="closeExam">取消</button></div></div></div>`;$('#again').onclick=()=>{$('#modal').innerHTML='';newPercent('exam',true)};$('#closeExam').onclick=()=>{$('#modal').innerHTML=''}}
setInterval(()=>{[['p',st.percent],['m',st.memory]].forEach(([id,s])=>{let e=$('#'+id+'Time');if(e)e.textContent=time(s.start?Math.floor((Date.now()-s.start)/1000):0)});if(st.percent.mode==='exam'&&st.percent.deadline){let n=examLeft(),e=$('#examLeft');if(e)e.textContent=time(n);if(n<=0)finishExam()}},250);
$$('.nav button').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));st.percent.q={};newPercent('b2f',true);newMemory('square','forward',true);renderCheat();switchPage('percent');
